root: true
extends: airbnb
rules:
  max-len: off
  no-console: off
  no-else-return: off
  no-plusplus: off
  no-unexpected-multiline: error
  semi:
    - error
    - never
env:
  es6: true
  node: true
